# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
os:
  - linux
  - osx

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'Corona19:::refresh_corona_data()'
  skip_cleanup: true
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
